apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: loki
    url: http://loki:3100
    isDefault: false
    editable: false
    jsonData:
      maxLines: 1000
