services:
  demo-fastapi-rolldice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-fastapi-rolldice
    ports:
      - "8001:8001"
    environment:
      - OTEL_SERVICE_NAME=dice-roller
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    networks:
      - monitoring
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \"import urllib.request; urllib.request.urlopen('http://localhost:8001/metrics')\" || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  monitoring:
    external: true
