services:
  demo-fastapi-rolldice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-fastapi-rolldice
    ports:
      - "8001:8001"
    environment:
      - OTEL_SERVICE_NAME=dice-roller
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    networks:
      - monitoring
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
        loki-external-labels: "job=demo-fastapi-rolldice,container_name=demo-fastapi-rolldice"

networks:
  monitoring:
    external: true
