[project]
name = "usage-stats-receiver"
version = "0.1.0"
description = "HTTP receiver for usage statistics log events"
requires-python = ">=3.13"
dependencies = [
    "psycopg2-binary>=2.9.10",
    "requests>=2.32.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
