networks:
  monitoring:
    external: true

services:
  die-service:
    build: ./die-service
    container_name: die-service-stage3
    ports:
      - "8103:8000"
    environment:
      - OTEL_SERVICE_NAME=die-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://alloy:4318/v1/traces
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    networks:
      - monitoring
    labels:
      com.docker.compose.project: "stage3-die-service"
      com.docker.compose.service: "die-service"
    restart: unless-stopped

  dice-roller:
    build: ./dice-roller
    container_name: dice-roller-stage3
    ports:
      - "8104:8000"
    environment:
      - OTEL_SERVICE_NAME=dice-roller
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://alloy:4318/v1/traces
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    networks:
      - monitoring
    labels:
      com.docker.compose.project: "stage3-dice-roller"
      com.docker.compose.service: "dice-roller"
    depends_on:
      - die-service
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend-stage3
    ports:
      - "8105:8000"
    environment:
      - OTEL_SERVICE_NAME=frontend
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://alloy:4318/v1/traces
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    networks:
      - monitoring
    labels:
      com.docker.compose.project: "stage3-frontend"
      com.docker.compose.service: "frontend"
    depends_on:
      - dice-roller
      - die-service
    restart: unless-stopped
