services:
  shiny-curl-gui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shiny-curl-gui
    ports:
      - "8002:3838"
    environment:
      - OTEL_SERVICE_NAME=shiny-curl-gui
      - OTEL_R_TRACES_EXPORTER=http
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://alloy:4318/v1/traces
    networks:
      - monitoring
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "Rscript -e \"httr2::request('http://localhost:3838/') |> httr2::req_perform() |> httr2::resp_status()\" || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  monitoring:
    external: true
