services:
  shiny-curl-gui:
    build:
      dockerfile: Dockerfile
    container_name: shiny-curl-gui
    ports:
      - "8002:3838"
    networks:
      - monitoring
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
        loki-external-labels: "job=shiny-curl-gui,container_name=shiny-curl-gui"

networks:
  monitoring:
    external: true
